version: '3.8'

services:
    db:
        image: mariadb:10.6
        restart: always
        environment:
            - MARIADB_DATABASE=panu
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
            - MARIADB_USER=panu
            - MARIADB_RANDOM_ROOT_PASSWORD=1
        volumes:
            - ./db/data:/var/lib/mysql
        networks:
            - back-tier
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5
    panu:
        build:
            context: .
            args:
                EXTERNAL_URL: ${EXTERNAL_URL}
        depends_on:
            - db
        restart: always
        networks:
            - back-tier
        command: sh -c './wait-for db:3306 -- python3 panu.py'
    shortener:
        image: php:8.0-apache
        build: shortener/
        networks:
            - front-tier
            - back-tier
        ports:
            - 80:80
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.shortener.rule=Host(`${LETSENCRYPT_DOMAIN}`)"
            - "traefik.http.routers.shortener.entrypoints=websecure"
            - "traefik.http.routers.shortener.tls.certresolver=myresolver"
    traefik:
        image: traefik:v2.5
        volumes:
            # So that Traefik can listen to the Docker events
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./letsencrypt:/letsencrypt"
        ports:
            - "443:443"
            - "8080:8080"
        networks:
            - front-tier
            - back-tier
        command:
            - "--api.insecure=false"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

networks:
  back-tier:
  front-tier:
